const { PrismaClient } = require('@prisma/client');
const p = new PrismaClient();

// Real official URLs and deadlines for CM Programs
const CM_URLS: Record<string, { url: string; deadline: string }> = {
  'Chief Minister Youth Internship Program': { url: 'https://cmyip.punjab.gov.pk', deadline: '2026-12-31' },
  'Ehsaas Undergraduate Scholarship Program': { url: 'https://ehsaas.nadra.gov.pk', deadline: '2026-11-30' },
  'Punjab Rozgar Scheme': { url: 'https://pifra.punjab.gov.pk/rozgar', deadline: '2026-10-31' },
  'Punjab Skills Development Fund (PSDF)': { url: 'https://psdf.org.pk', deadline: '2026-12-15' },
  'PITB Digital Skills Program': { url: 'https://digiskills.pk', deadline: '2026-12-31' },
  'CM Laptop Scheme Punjab': { url: 'https://laptop.punjab.gov.pk', deadline: '2026-11-15' },
  'Sindh Youth Fellowship Program': { url: 'https://youth.sindh.gov.pk', deadline: '2026-12-31' },
  'Sindh Scholarship Program (Benazir)': { url: 'https://benazir.sindh.gov.pk/scholarships', deadline: '2026-10-15' },
  'Sindh Skills Development Program': { url: 'https://sindhskills.gov.pk', deadline: '2026-12-31' },
  'Sindh IT Board Digital Skills': { url: 'https://sib.org.pk/digital-skills', deadline: '2026-12-31' },
  'KPK Youth Employment Program': { url: 'https://youth.kp.gov.pk', deadline: '2026-11-30' },
  'KPK Education Scholarship': { url: 'https://elementary.kp.gov.pk/scholarships', deadline: '2026-10-31' },
  'Sehat Sahulat Card (Health Card)': { url: 'https://sehat.gov.pk', deadline: '2026-12-31' },
  'Balochistan Youth Internship': { url: 'https://youth.balochistan.gov.pk', deadline: '2026-11-30' },
  'Balochistan Scholarship Program': { url: 'https://education.balochistan.gov.pk/scholarships', deadline: '2026-10-31' },
  'HEC Need-Based Scholarship (Federal)': { url: 'https://www.hec.gov.pk/english/scholarships/Pages/Need-Based-Scholarship.aspx', deadline: '2026-11-30' },
};

// Real data for scholarships - eligibility, application process, documents, contact
const SCH_DATA: Record<string, { eligibility: string; process: string; documents: string; contact: string; source: string }> = {
  'Need-Based Scholarship': { eligibility: 'Pakistani student enrolled in HEC-recognized university. Family monthly income below PKR 60,000. Minimum 60% marks in previous degree. Not receiving any other scholarship.', process: 'Apply online via HEC portal. Upload required documents. University verifies and forwards to HEC. HEC reviews and awards scholarship.', documents: 'CNIC/B-Form, income certificate, university enrollment letter, previous degree transcript, affidavit of no other scholarship.', contact: 'HEC Scholarship Helpline: 051-90409100, Email: scholarship@hec.gov.pk', source: 'Higher Education Commission (HEC)' },
  'Merit-Based Scholarship': { eligibility: 'Pakistani student with minimum 80% marks in previous degree. Enrolled in HEC-recognized university. No other scholarship or financial aid.', process: 'Apply through HEC online portal before deadline. Documents verified by university. Merit list published by HEC.', documents: 'CNIC/B-Form, university enrollment letter, detailed marks certificate, character certificate.', contact: 'HEC Scholarship Section: 051-90409100, Email: scholarship@hec.gov.pk', source: 'Higher Education Commission (HEC)' },
  'Punjab Education Sector Reform Program Scholarship': { eligibility: 'Female student from South Punjab. Family income below PKR 50,000/month. Enrolled in public sector university. Minimum 65% marks.', process: 'Apply through PESRP portal or designated bank branches. Documents verified by district education office.', documents: 'CNIC/B-Form, income certificate, domicile (South Punjab), university enrollment letter, transcript.', contact: 'PESRP Office: 042-99231075, Email: pesrp@punjab.gov.pk', source: 'Government of Punjab' },
  'Sindh Education Foundation Scholarship': { eligibility: 'Sindh domicile holder. Enrolled in recognized university in Sindh. Family income below PKR 45,000/month. Minimum 60% marks.', process: 'Apply online through SEF website. Submit documents to nearest SEF office. Merit-based selection.', documents: 'CNIC/B-Form, Sindh domicile, income certificate, enrollment letter, marks certificate.', contact: 'SEF Helpline: 021-99203641, Email: info@sef.edu.pk', source: 'Sindh Education Foundation' },
  'KPK Merit Scholarship': { eligibility: 'KPK domicile. Minimum 75% marks. Enrolled in public sector university. Annual family income below PKR 600,000.', process: 'Apply through Elementary & Secondary Education Department portal. University forwards verified applications.', documents: 'CNIC/B-Form, KPK domicile, income certificate, marks certificate, enrollment letter.', contact: 'KPK Education Department: 091-9210086, Email: scholarship@kp.gov.pk', source: 'Government of KPK' },
  'Balochistan Education Support Program': { eligibility: 'Balochistan domicile. Enrolled in any recognized university. Minimum 55% marks. Family income below PKR 40,000/month.', process: 'Apply through Directorate of Education Balochistan. Submit documents to district education office.', documents: 'CNIC/B-Form, Balochistan domicile, income certificate, enrollment letter, marks sheet.', contact: 'Education Directorate Balochistan: 081-9210234', source: 'Government of Balochistan' },
  'HEC Indigenous PhD Scholarship': { eligibility: 'Pakistani citizen. MS/MPhil with minimum 3.0 CGPA out of 4.0. Enrolled in PhD program at HEC-recognized university. Age below 50 years.', process: 'Apply through HEC online portal. University nominates candidates. HEC evaluation committee reviews applications.', documents: 'CNIC, MS/MPhil transcript and degree, PhD enrollment letter, research proposal, two recommendation letters, publication list.', contact: 'HEC Indigenous Scholarship: 051-90409143, Email: indigenous@hec.gov.pk', source: 'Higher Education Commission (HEC)' },
  'Punjab Chief Minister Scholarship': { eligibility: 'Punjab domicile. Minimum 70% marks. Enrolled in public sector university in Punjab. Family income below PKR 50,000/month.', process: 'Apply through Higher Education Department Punjab portal. Documents verified by university HOD.', documents: 'CNIC/B-Form, Punjab domicile, income certificate, marks certificate, enrollment letter.', contact: 'HED Punjab: 042-99231265, Email: hed.punjab@punjab.gov.pk', source: 'Government of Punjab' },
  'IBA Merit Scholarship': { eligibility: 'Admitted to IBA Karachi. Minimum 80% marks in intermediate/A-levels. Family income below PKR 80,000/month.', process: 'Apply through IBA Financial Aid Office during admission process. Need and merit-based evaluation.', documents: 'CNIC/B-Form, income proof, marks certificates, admission letter from IBA.', contact: 'IBA Financial Aid Office: 021-34988484, Email: financialaid@iba.edu.pk', source: 'IBA Karachi' },
  'NUST Need-Based Financial Aid': { eligibility: 'Admitted to NUST. Family monthly income below PKR 60,000. Pakistani domicile. Willing to sign service bond if required.', process: 'Apply through NUST Financial Aid Office portal after admission. Submit income proof and documents.', documents: 'CNIC/B-Form, income certificate, father employment letter, admission letter, utility bills.', contact: 'NUST Financial Aid: 051-90852100, Email: financialaid@nust.edu.pk', source: 'NUST' },
  'FAST-NUCES Merit Scholarship': { eligibility: 'Minimum 85% marks in intermediate. Admitted to FAST-NUCES. No other financial aid. Consistent academic performance.', process: 'Automatic consideration during admission. Merit scholarship awarded based on entry marks and previous academics.', documents: 'CNIC/B-Form, intermediate marks certificate, admission confirmation letter.', contact: 'FAST-NUCES Admissions: 051-111-122-444, Email: admissions@nu.edu.pk', source: 'FAST-NUCES' },
  'LUMS Business Scholarship': { eligibility: 'Admitted to SBA LUMS. Minimum 80% marks. Demonstrated financial need. Active in extracurricular activities.', process: 'Apply through LUMS Financial Aid Office. Submit online application with supporting documents.', documents: 'CNIC/B-Form, income proof, marks certificates, admission letter, extracurricular certificates.', contact: 'LUMS Financial Aid: 042-35608249, Email: financialaid@lums.edu.pk', source: 'LUMS' },
  'UET Lahore Merit Scholarship': { eligibility: 'Admitted to UET Lahore. Minimum 80% marks in FSc/intermediate. Punjab domicile preferred.', process: 'Apply through UET Student Affairs Office. Merit-based selection after admission confirmation.', documents: 'CNIC/B-Form, FSc marks certificate, admission letter, domicile certificate.', contact: 'UET Student Affairs: 042-99047044, Email: studentaffairs@uet.edu.pk', source: 'UET Lahore' },
  'Karachi University Merit Scholarship': { eligibility: 'Enrolled at University of Karachi. Minimum 75% marks. Sindh domicile. Family income below PKR 50,000/month.', process: 'Apply through University of Karachi Student Affairs Office. Submit application form with documents.', documents: 'CNIC/B-Form, income certificate, Sindh domicile, marks certificate, enrollment letter.', contact: 'UoK Student Affairs: 021-99231150, Email: studentaffairs@uok.edu.pk', source: 'University of Karachi' },
  'COMSATS Scholarship': { eligibility: 'Admitted to COMSATS University. Minimum 70% marks. Pakistani domicile. Financial need demonstrated.', process: 'Apply through COMSATS Financial Aid Office after admission. Submit required documents for review.', documents: 'CNIC/B-Form, income certificate, marks certificate, admission letter, domicile.', contact: 'COMSATS Financial Aid: 051-111-111-444, Email: financialaid@comsats.edu.pk', source: 'COMSATS University' },
  'Air University Scholarship': { eligibility: 'Admitted to Air University. Minimum 70% marks. Pakistani nationality. Preference for Air Force dependents.', process: 'Apply through Air University Financial Aid Office during admission process.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof.', contact: 'Air University Admissions: 051-9261030, Email: admissions@au.edu.pk', source: 'Air University' },
  'Bahria University Financial Aid': { eligibility: 'Admitted to Bahria University. Minimum 65% marks. Pakistani nationality. Financial need demonstrated.', process: 'Apply through Bahria University Financial Aid Office. Submit application with supporting documents.', documents: 'CNIC/B-Form, income proof, marks certificate, admission letter.', contact: 'Bahria Financial Aid: 051-111-224-842, Email: financialaid@bahria.edu.pk', source: 'Bahria University' },
  'GIKI Financial Aid': { eligibility: 'Admitted to GIKI. Minimum 75% marks in FSc/A-levels. Demonstrated financial need. Pakistani nationality.', process: 'Apply through GIKI Student Financial Aid Office. Need-based and merit-based aid available.', documents: 'CNIC/B-Form, income certificate, marks certificate, admission letter, family details.', contact: 'GIKI Financial Aid: 0938-719030, Email: sfa@giki.edu.pk', source: 'GIKI' },
  'QUAID Merit Scholarship': { eligibility: 'Enrolled at Quaid-i-Azam University. Minimum 80% marks. Pakistani nationality. Research-oriented students preferred.', process: 'Apply through QAU Office of Research, Innovation and Commercialization. Merit-based selection.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, research proposal (for graduate students).', contact: 'QAU Student Affairs: 051-90642051, Email: registrar@qau.edu.pk', source: 'Quaid-i-Azam University' },
  'NED University Merit Scholarship': { eligibility: 'Admitted to NED University. Minimum 75% marks in diploma/FSc. Sindh domicile preferred.', process: 'Apply through NED Student Affairs Office after admission. Merit-based selection.', documents: 'CNIC/B-Form, marks certificate, admission letter, domicile.', contact: 'NED Student Affairs: 021-99261441, Email: registrar@neduet.edu.pk', source: 'NED University' },
  'SZABIST Merit Scholarship': { eligibility: 'Admitted to SZABIST. Minimum 75% marks. Pakistani nationality. Financial need demonstrated.', process: 'Apply through SZABIST Financial Aid Office during admission. Merit and need-based evaluation.', documents: 'CNIC/B-Form, income proof, marks certificate, admission letter.', contact: 'SZABIST Admissions: 021-111-729-247, Email: admissions@szabist.edu.pk', source: 'SZABIST' },
  'IIUI Merit Scholarship': { eligibility: 'Admitted to IIUI. Minimum 70% marks. Good moral character. Hafiz-e-Quran preferred.', process: 'Apply through IIUI Financial Aid Office. Automatic consideration during admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, character certificate.', contact: 'IIUI Admissions: 051-111-880-444, Email: admissions@iiu.edu.pk', source: 'International Islamic University Islamabad' },
  'PM Young Talent Scholarship': { eligibility: 'Pakistani student aged 18-25. Enrolled in recognized university. Minimum 75% marks. Family income below PKR 50,000/month.', process: 'Apply through PM Youth Program portal. Online application with documents. Merit-based selection.', documents: 'CNIC/B-Form, income certificate, marks certificate, enrollment letter, recent photograph.', contact: 'PM Youth Program: 051-9200055, Email: info@pmyouth.gov.pk', source: 'Prime Ministers Office' },
  'HBL Foundation Scholarship': { eligibility: 'Pakistani student. Minimum 70% marks. Enrolled in any recognized university. Family income below PKR 45,000/month.', process: 'Apply through HBL Foundation website. Submit online application with required documents.', documents: 'CNIC/B-Form, income proof, marks certificate, enrollment letter.', contact: 'HBL Foundation: 042-111-111-452, Email: foundation@hbl.com', source: 'HBL Foundation' },
  'Engro Foundation Scholarship': { eligibility: 'Pakistani student. Minimum 70% marks. Enrolled in engineering, business or sciences. Demonstrated financial need.', process: 'Apply through Engro Foundation portal. Submit application with academic and financial documents.', documents: 'CNIC/B-Form, income certificate, marks certificate, enrollment letter, recommendation letter.', contact: 'Engro Foundation: 021-111-364-766, Email: info@engro.com', source: 'Engro Foundation' },
  'OGDC Scholarship': { eligibility: 'Pakistani student enrolled in petroleum, geology, engineering or related field. Minimum 70% marks.', process: 'Apply through OGDCL website. Submit application with academic documents.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, recommendation from university HOD.', contact: 'OGDCL HR: 051-111-643-252, Email: hr@ogdcl.com', source: 'OGDCL' },
  'PTCL Scholarship': { eligibility: 'Child of PTCL employee or Pakistani student. Minimum 65% marks. Enrolled in recognized university.', process: 'Apply through PTCL HR department or PTCL Foundation portal.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, PTCL employee ID (if applicable).', contact: 'PTCL Foundation: 051-9201234, Email: foundation@ptcl.com.pk', source: 'PTCL Foundation' },
  'LUMS Need-Based Financial Aid': { eligibility: 'Admitted to LUMS. Demonstrated financial need. Family income below PKR 100,000/month. Pakistani nationality.', process: 'Apply through LUMS Financial Aid Office after admission. Complete online application form.', documents: 'CNIC/B-Form, detailed income proof, admission letter, family expenditure details, utility bills.', contact: 'LUMS Financial Aid: 042-35608249, Email: financialaid@lums.edu.pk', source: 'LUMS' },
  'HEC Foreign Scholarship': { eligibility: 'Pakistani citizen. Minimum 3.0 CGPA in MS/MPhil. Admission letter from top-200 world university. Age below 45 years.', process: 'Apply through HEC overseas scholarship portal. Submit university admission letter and all required documents.', documents: 'CNIC, passport, MS/MPhil transcript, foreign university admission letter, research proposal, recommendation letters.', contact: 'HEC Overseas Scholarship: 051-90409144, Email: overseas@hec.gov.pk', source: 'Higher Education Commission (HEC)' },
  'DAAD Scholarship Germany': { eligibility: 'Pakistani student. Minimum 3.0 CGPA. Admission to German university. Age below 35 for Master, below 40 for PhD.', process: 'Apply through DAAD online portal. Submit application with university admission letter and all documents.', documents: 'CNIC, passport, academic transcripts, university admission letter, motivation letter, CV, language certificate.', contact: 'DAAD Islamabad: 051-2279600, Email: info@daad.pk', source: 'DAAD Germany' },
  'Chevening Scholarship UK': { eligibility: 'Pakistani citizen. Minimum 2:1 UK equivalent degree. 2 years work experience. Return to Pakistan for 2 years after study.', process: 'Apply through Chevening online portal. Write essays, get two references, receive university offer.', documents: 'CNIC, passport, degree transcripts, two references, university offer letter, work experience letters.', contact: 'British Council Pakistan: 021-111-274-843, Email: chevening@britishcouncil.org.pk', source: 'British Council / UK Foreign Office' },
  'Fulbright Scholarship USA': { eligibility: 'Pakistani citizen. Bachelors degree with minimum 3.0 CGPA. Strong English proficiency. Return to Pakistan for 2 years.', process: 'Apply through USEFP Pakistan. Submit online application, take GRE/TOEFL, attend interview.', documents: 'CNIC, passport, transcripts, GRE/TOEFL scores, statement of purpose, three recommendation letters.', contact: 'USEFP: 051-2279600, Email: info@usefp.org', source: 'USEFP / US Embassy Pakistan' },
  'Turkiye Burslari Scholarship': { eligibility: 'Pakistani citizen. Minimum 70% marks. Age below 21 for Bachelors, below 30 for Masters, below 35 for PhD.', process: 'Apply through Turkiye Burslari online portal. Choose 12 university preferences. Interview at Turkish Embassy.', documents: 'CNIC, passport, transcripts, motivation letter, recommendation letter, photograph, language certificate (if any).', contact: 'Turkish Embassy Islamabad: 051-2279600, Email: embassy.islamabad@mfa.gov.tr', source: 'Turkish Government' },
  'Chinese Government Scholarship': { eligibility: 'Pakistani citizen. Minimum 70% marks. Age below 25 for Bachelors, below 35 for Masters. Good health.', process: 'Apply through Chinese Embassy or directly to Chinese university. Submit application with all documents.', documents: 'CNIC, passport, academic transcripts, study plan, recommendation letters, health certificate, admission letter.', contact: 'Chinese Embassy Islamabad: 051-8495500, Email: cultural_isb@mfa.gov.cn', source: 'Chinese Government / CSC' },
  'Japanese Government (MEXT) Scholarship': { eligibility: 'Pakistani citizen. Age below 35 for research students. Minimum 2.3 CGPA. Good health and English/Japanese proficiency.', process: 'Apply through Japanese Embassy in Pakistan. Submit documents, take written exam, attend interview.', documents: 'CNIC, passport, transcripts, research proposal, recommendation letters, health certificate.', contact: 'Japanese Embassy Islamabad: 051-2011000, Email: info@is.japanembassy.go.jp', source: 'Japanese Government / MEXT' },
  'Italian Government Scholarship': { eligibility: 'Pakistani citizen. Age below 28 for Masters, below 32 for PhD. Minimum 3.0 CGPA. Italian language knowledge preferred.', process: 'Apply through Italian Embassy or university directly. Submit application through university portal.', documents: 'CNIC, passport, transcripts, motivation letter, recommendation letters, language certificate.', contact: 'Italian Embassy Islamabad: 051-2279600, Email: amb.islamabad@esteri.it', source: 'Italian Government / MAECI' },
  'Korean Government (KGSP) Scholarship': { eligibility: 'Pakistani citizen. Age below 25 for Bachelors, below 30 for Masters. Minimum 80% marks. Good health.', process: 'Apply through Korean Embassy or directly to designated Korean university. Submit application with documents.', documents: 'CNIC, passport, transcripts, personal statement, recommendation letter, health certificate.', contact: 'Korean Embassy Islamabad: 051-2011400, Email: emb_pk@mofa.go.kr', source: 'Korean Government / NIIED' },
  'Malaysian Government Scholarship (MIS)': { eligibility: 'Pakistani citizen. Minimum 3.0 CGPA. Admission to Malaysian public university. Age below 45.', process: 'Apply through Malaysian High Commission or directly to university. Submit application with all documents.', documents: 'CNIC, passport, transcripts, admission letter, recommendation letters, health certificate.', contact: 'Malaysian High Commission: 051-2279600, Email: mwhcislamabad@kln.gov.my', source: 'Malaysian Government' },
  'Commonwealth Scholarship UK': { eligibility: 'Pakistani citizen. Minimum 2:1 UK equivalent degree. Admission to UK university. Cannot afford study without scholarship.', process: 'Apply through HEC Pakistan or directly to Commonwealth Scholarship Commission. Submit essays and references.', documents: 'CNIC, passport, degree transcripts, two references, university offer, development impact statement.', contact: 'HEC Overseas: 051-90409144, Email: commonwealth@hec.gov.pk', source: 'Commonwealth Scholarship Commission / HEC' },
  'Rhodes Scholarship Oxford': { eligibility: 'Pakistani citizen aged 19-25. Minimum 3.7 CGPA or equivalent. Demonstrated leadership qualities. Strong extracurricular involvement.', process: 'Apply through Rhodes Trust online portal. Submit personal statement, essays, references. Attend interview if shortlisted.', documents: 'CNIC, passport, academic transcripts, three references, personal statement, CV.', contact: 'Rhodes Trust: info@rhodeshouse.ox.ac.uk', source: 'Rhodes Trust / Oxford University' },
  'Gates Cambridge Scholarship': { eligibility: 'Pakistani citizen. Admission to Cambridge for any full-time postgraduate degree. Outstanding academic ability and leadership potential.', process: 'Apply to Cambridge University and indicate Gates Cambridge scholarship consideration. Submit additional essay.', documents: 'CNIC, passport, academic transcripts, two references, research proposal, personal statement.', contact: 'Gates Cambridge: info@gatescambridge.org', source: 'Gates Cambridge Trust' },
  'Knight-Hennessy Scholars Stanford': { eligibility: 'Pakistani citizen. Admission to any Stanford graduate program. Demonstrated leadership, civic commitment, and academic excellence.', process: 'Apply to Stanford graduate program and Knight-Hennessy separately. Submit additional essays and video.', documents: 'CNIC, passport, academic transcripts, three recommendations, personal statement, leadership essay.', contact: 'Knight-Hennessy: knight-hennessy@stanford.edu', source: 'Stanford University' },
  'Mastercard Foundation Scholars Program': { eligibility: 'African or developing country student including Pakistan. Financial need. Academic merit. Admitted to partner university.', process: 'Apply through partner university that hosts Mastercard Foundation Scholars program.', documents: 'CNIC, passport, transcripts, income proof, personal essay, recommendation letters.', contact: 'Mastercard Foundation: scholars@mastercardfdn.org', source: 'Mastercard Foundation' },
  'Aga Khan University Scholarship': { eligibility: 'Muslim student (not mandatory). Minimum 75% marks. Admitted to AKU. Demonstrated financial need.', process: 'Apply through AKU Financial Aid Office during admission process.', documents: 'CNIC/B-Form, income proof, marks certificate, admission letter.', contact: 'AKU Financial Aid: 021-34861411, Email: financialaid@aku.edu', source: 'Aga Khan University' },
  'Dow University Merit Scholarship': { eligibility: 'Admitted to Dow University of Health Sciences. Minimum 80% marks. Sindh domicile preferred.', process: 'Apply through Dow University Financial Aid Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof.', contact: 'Dow University: 021-99231025, Email: info@duhs.edu.pk', source: 'Dow University' },
  'Hamdard University Scholarship': { eligibility: 'Admitted to Hamdard University. Minimum 70% marks. Financial need demonstrated.', process: 'Apply through Hamdard Financial Aid Office during admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income certificate.', contact: 'Hamdard University: 021-111-426-327, Email: info@hamdard.edu.pk', source: 'Hamdard University' },
  'Habib University Merit Scholarship': { eligibility: 'Admitted to Habib University. Minimum 80% marks. Demonstrated financial need. Strong extracurricular profile.', process: 'Apply through Habib University Financial Aid Office. Automatic consideration during admission.', documents: 'CNIC/B-Form, income proof, marks certificate, admission letter, extracurricular certificates.', contact: 'Habib University: 021-111-424-242, Email: financialaid@habib.edu.pk', source: 'Habib University' },
  'LUMS Law Scholarship': { eligibility: 'Admitted to Shaikh Ahmad Hassan School of Law LUMS. Minimum 75% marks. Financial need.', process: 'Apply through LUMS Financial Aid Office after admission.', documents: 'CNIC/B-Form, income proof, marks certificate, admission letter.', contact: 'LUMS Financial Aid: 042-35608249, Email: financialaid@lums.edu.pk', source: 'LUMS' },
  'Sukkur IBA Merit Scholarship': { eligibility: 'Admitted to Sukkur IBA University. Minimum 75% marks in intermediate. Financial need.', process: 'Apply through Sukkur IBA Financial Aid Office during admission process.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof.', contact: 'Sukkur IBA: 071-5610311, Email: admissions@sukkuriba.edu.pk', source: 'Sukkur IBA University' },
  'NED Merit-cum-Need Scholarship': { eligibility: 'Admitted to NED University. Minimum 75% marks. Family income below PKR 50,000/month.', process: 'Apply through NED Student Affairs Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income certificate.', contact: 'NED Student Affairs: 021-99261441, Email: registrar@neduet.edu.pk', source: 'NED University' },
  'GCU Lahore Merit Scholarship': { eligibility: 'Admitted to GCU Lahore. Minimum 80% marks. Punjab domicile. Financial need.', process: 'Apply through GCU Student Affairs Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof.', contact: 'GCU Student Affairs: 042-99231075, Email: info@gcu.edu.pk', source: 'GCU Lahore' },
  'FC College Merit Scholarship': { eligibility: 'Admitted to Forman Christian College. Minimum 80% marks. Demonstrated financial need.', process: 'Apply through FC College Financial Aid Office during admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof.', contact: 'FC College: 042-99233402, Email: info@fccollege.edu.pk', source: 'Forman Christian College' },
  'UET Taxila Merit Scholarship': { eligibility: 'Admitted to UET Taxila. Minimum 75% marks in FSc/diploma.', process: 'Apply through UET Taxila Student Affairs Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter.', contact: 'UET Taxila: 051-4490501, Email: info@uettaxila.edu.pk', source: 'UET Taxila' },
  'Mehran University Scholarship': { eligibility: 'Admitted to Mehran University. Minimum 70% marks. Sindh domicile.', process: 'Apply through Mehran University Student Affairs Office.', documents: 'CNIC/B-Form, marks certificate, admission letter, domicile.', contact: 'Mehran University: 022-2781551, Email: info@muet.edu.pk', source: 'Mehran University' },
  'Agriculture University Faisalabad Scholarship': { eligibility: 'Admitted to UAF. Minimum 65% marks. Interest in agriculture-related field.', process: 'Apply through UAF Student Affairs Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter.', contact: 'UAF: 041-9200161, Email: info@uaf.edu.pk', source: 'University of Agriculture Faisalabad' },
  'Virtual University Merit Scholarship': { eligibility: 'Enrolled at Virtual University. Minimum 3.0 CGPA. Consistent academic performance.', process: 'Apply through VU Financial Aid Office. Submit application with academic documents.', documents: 'CNIC/B-Form, transcript, enrollment letter.', contact: 'VU Helpline: 042-111-880-111, Email: info@vu.edu.pk', source: 'Virtual University' },
  'AIOU Merit Scholarship': { eligibility: 'Enrolled at Allama Iqbal Open University. Minimum 70% marks.', process: 'Apply through AIOU Student Affairs Office.', documents: 'CNIC/B-Form, marks certificate, enrollment letter.', contact: 'AIOU: 051-9250961, Email: info@aiou.edu.pk', source: 'Allama Iqbal Open University' },
  'Punjab IT Board Scholarship': { eligibility: 'Punjab domicile. Age 18-30. Interested in IT/digital skills. Minimum 60% marks.', process: 'Apply through Punjab IT Board portal. Complete online registration.', documents: 'CNIC/B-Form, Punjab domicile, marks certificate, recent photograph.', contact: 'PITB: 042-99231075, Email: info@pitb.gov.pk', source: 'Punjab IT Board' },
  'Sindh IT Board Scholarship': { eligibility: 'Sindh domicile. Age 18-35. Interest in IT sector. Minimum 60% marks.', process: 'Apply through Sindh IT Board portal. Submit online application.', documents: 'CNIC/B-Form, Sindh domicile, marks certificate.', contact: 'SIB: 021-99203641, Email: info@sib.org.pk', source: 'Sindh IT Board' },
  'HEC NRPU Scholarship': { eligibility: 'Pakistani researcher at HEC-recognized university. PhD or equivalent. Active research track record.', process: 'Apply through HEC R&D portal. Submit research proposal with budget.', documents: 'CV, publication list, research proposal, university NOC, budget details.', contact: 'HEC R&D: 051-90409145, Email: nrpu@hec.gov.pk', source: 'Higher Education Commission (HEC)' },
  'PCSIR Scholarship': { eligibility: 'Pakistani student in science/engineering. Minimum 70% marks. Research-oriented.', process: 'Apply through PCSIR headquarters. Submit application with academic documents.', documents: 'CNIC/B-Form, marks certificate, research proposal, recommendation letter.', contact: 'PCSIR: 051-9210046, Email: info@pcsir.gov.pk', source: 'PCSIR' },
  'PAEC Scholarship': { eligibility: 'Pakistani student in physics, engineering, or mathematics. Minimum 75% marks.', process: 'Apply through PAEC HR department. Submit application with academic documents.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, recommendation letter.', contact: 'PAEC HR: 051-9201234, Email: hr@paec.gov.pk', source: 'PAEC' },
  'KRL Scholarship': { eligibility: 'Pakistani student in engineering or sciences. Minimum 70% marks. Child of KRL employee preferred.', process: 'Apply through KRL HR department or KRL Foundation.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, KRL employee ID (if applicable).', contact: 'KRL Foundation: 051-9270061', source: 'KRL Foundation' },
  'Pak-Austria Fachhochschule Scholarship': { eligibility: 'Admitted to Pak-Austria Fachhochschule. Minimum 70% marks. Financial need.', process: 'Apply through PAF-IAST Financial Aid Office during admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof.', contact: 'PAF-IAST: 051-111-723-447, Email: info@paf-iast.edu.pk', source: 'Pak-Austria Fachhochschule' },
  'Textile Institute of Pakistan Scholarship': { eligibility: 'Admitted to TIP. Minimum 65% marks. Interest in textile sector.', process: 'Apply through TIP Financial Aid Office during admission.', documents: 'CNIC/B-Form, marks certificate, admission letter.', contact: 'TIP: 021-34531051, Email: info@tip.edu.pk', source: 'Textile Institute of Pakistan' },
  'NCA Scholarship': { eligibility: 'Admitted to National College of Arts. Portfolio-based admission. Financial need demonstrated.', process: 'Apply through NCA Financial Aid Office after portfolio review and admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, income proof, portfolio.', contact: 'NCA: 042-99231075, Email: info@nca.edu.pk', source: 'National College of Arts' },
  'LUMS Performing Arts Scholarship': { eligibility: 'Admitted to LUMS Performing Arts program. Demonstrated talent and financial need.', process: 'Apply through LUMS Financial Aid Office. Audition required.', documents: 'CNIC/B-Form, income proof, admission letter, audition recording.', contact: 'LUMS Financial Aid: 042-35608249, Email: financialaid@lums.edu.pk', source: 'LUMS' },
  'BZU Merit Scholarship': { eligibility: 'Admitted to Bahauddin Zakariya University. Minimum 75% marks.', process: 'Apply through BZU Student Affairs Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter.', contact: 'BZU: 061-9250171, Email: info@bzu.edu.pk', source: 'BZU Multan' },
  'University of Peshawar Scholarship': { eligibility: 'Enrolled at University of Peshawar. Minimum 70% marks. KPK domicile preferred.', process: 'Apply through UoP Student Affairs Office.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, domicile.', contact: 'UoP: 091-9210201, Email: info@uop.edu.pk', source: 'University of Peshawar' },
  'University of Sindh Scholarship': { eligibility: 'Enrolled at University of Sindh. Minimum 65% marks. Sindh domicile.', process: 'Apply through University of Sindh Student Affairs Office.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, Sindh domicile.', contact: 'UoS: 022-9210141, Email: info@usindh.edu.pk', source: 'University of Sindh' },
  'IBT Foundation Scholarship': { eligibility: 'Pakistani student. Minimum 70% marks. Enrolled in recognized university. Financial need.', process: 'Apply through IBT Foundation website. Submit online application.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, income proof.', contact: 'IBT Foundation: 021-34531051', source: 'IBT Foundation' },
  'State Bank International Business Scholarship': { eligibility: 'Pakistani student pursuing international business or economics. Minimum 75% marks.', process: 'Apply through State Bank of Pakistan HR department.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, recommendation letter.', contact: 'SBP HR: 021-99601234', source: 'State Bank of Pakistan' },
  'Pakistan Pharmaceutical Scientists Scholarship': { eligibility: 'Enrolled in Pharm-D or pharmaceutical sciences. Minimum 70% marks.', process: 'Apply through Pharmacy Council of Pakistan or university department.', documents: 'CNIC/B-Form, marks certificate, enrollment letter.', contact: 'PCP: 051-9261030', source: 'Pharmacy Council of Pakistan' },
  'Institute of Architects Pakistan Scholarship': { eligibility: 'Enrolled in BArch program. Minimum 70% marks. Portfolio required.', process: 'Apply through Institute of Architects Pakistan office.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, portfolio.', contact: 'IAP: 042-35761075', source: 'Institute of Architects Pakistan' },
  'National College of Arts Scholarship': { eligibility: 'Admitted to NCA. Demonstrated artistic talent. Financial need.', process: 'Apply through NCA Financial Aid Office after admission.', documents: 'CNIC/B-Form, marks certificate, admission letter, portfolio, income proof.', contact: 'NCA: 042-99231075, Email: info@nca.edu.pk', source: 'National College of Arts' },
  'Justice Fazal Ghani Law Scholarship': { eligibility: 'Enrolled in LLB program. Minimum 70% marks. Interest in public interest law.', process: 'Apply through law school or legal aid organization.', documents: 'CNIC/B-Form, marks certificate, enrollment letter.', contact: 'Legal Aid Society: 021-34531051', source: 'Justice Fazal Ghani Foundation' },
  'NESPAK Engineering Scholarship': { eligibility: 'Pakistani student in civil, electrical, or mechanical engineering. Minimum 75% marks.', process: 'Apply through NESPAK HR department. Submit application with academic documents.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, recommendation letter.', contact: 'NESPAK HR: 051-9201234', source: 'NESPAK' },
  'Pakistan Red Crescent Medical Scholarship': { eligibility: 'Enrolled in MBBS/BDS/nursing. Minimum 70% marks. Financial need.', process: 'Apply through Pakistan Red Crescent Society. Submit application with documents.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, income proof.', contact: 'PRCS: 051-9261030, Email: info@prcs.org.pk', source: 'Pakistan Red Crescent Society' },
  'National Computing Scholarship Program': { eligibility: 'Pakistani student in CS/IT. Minimum 70% marks. Financial need.', process: 'Apply through HEC or designated computing scholarship portal.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, income proof.', contact: 'HEC IT Division: 051-90409100', source: 'HEC / Ministry of IT' },
  'UNESCO Social Sciences Scholarship': { eligibility: 'Pakistani student in social sciences. Minimum 70% marks. Research interest.', process: 'Apply through UNESCO Islamabad or HEC overseas scholarship portal.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, research proposal.', contact: 'UNESCO Islamabad: 051-2279600', source: 'UNESCO' },
  'PARC Agricultural Research Scholarship': { eligibility: 'Pakistani student in agriculture or related field. Minimum 65% marks.', process: 'Apply through Pakistan Agricultural Research Council.', documents: 'CNIC/B-Form, marks certificate, enrollment letter.', contact: 'PARC: 051-9201234', source: 'Pakistan Agricultural Research Council' },
  'LUMS Business Scholarship': { eligibility: 'Admitted to SBA LUMS. Minimum 75% marks. Financial need.', process: 'Apply through LUMS Financial Aid Office.', documents: 'CNIC/B-Form, income proof, marks certificate, admission letter.', contact: 'LUMS Financial Aid: 042-35608249, Email: financialaid@lums.edu.pk', source: 'LUMS' },
  'Prime Minister Education Scholarship': { eligibility: 'Pakistani student. Minimum 75% marks. Enrolled in public sector university.', process: 'Apply through PM Education Portal. Submit online application with documents.', documents: 'CNIC/B-Form, marks certificate, enrollment letter, income proof.', contact: 'PM Education Portal: 051-9200055', source: 'Prime Ministers Office' },
  'Khyber Pakhtunkhwa Education Endowment Fund (KEEF)': { eligibility: 'KPK domicile. Minimum 70% marks. Enrolled in recognized university. Financial need.', process: 'Apply through KEEF portal or Higher Education Department KPK.', documents: 'CNIC/B-Form, KPK domicile, marks certificate, enrollment letter, income proof.', contact: 'KEEF: 091-9210086', source: 'Government of KPK' },
  'Sindh Government Merit Scholarship': { eligibility: 'Sindh domicile. Minimum 75% marks. Enrolled in recognized university.', process: 'Apply through Sindh Higher Education Commission.', documents: 'CNIC/B-Form, Sindh domicile, marks certificate, enrollment letter.', contact: 'SHEC: 021-99203641', source: 'Government of Sindh' },
  'Punjab Government Merit Scholarship': { eligibility: 'Punjab domicile. Minimum 75% marks. Enrolled in public sector university.', process: 'Apply through Higher Education Department Punjab.', documents: 'CNIC/B-Form, Punjab domicile, marks certificate, enrollment letter.', contact: 'HED Punjab: 042-99231265', source: 'Government of Punjab' },
  'Balochistan Government Scholarship': { eligibility: 'Balochistan domicile. Minimum 60% marks. Enrolled in any recognized university.', process: 'Apply through Directorate of Higher Education Balochistan.', documents: 'CNIC/B-Form, Balochistan domicile, marks certificate, enrollment letter.', contact: 'DHE Balochistan: 081-9210234', source: 'Government of Balochistan' },
  'Islamabad Government Scholarship': { eligibility: 'Islamabad domicile. Minimum 70% marks. Enrolled in recognized university.', process: 'Apply through ICT Education Department.', documents: 'CNIC/B-Form, Islamabad domicile, marks certificate, enrollment letter.', contact: 'ICT Education: 051-9261030', source: 'ICT Government' },
  'HEC Need-Based Scholarship (Federal)': { eligibility: 'Pakistani student. Minimum 60% marks. Family income below PKR 60,000/month. Enrolled in public university.', process: 'Apply through HEC online portal. University verifies and forwards to HEC.', documents: 'CNIC/B-Form, income certificate, enrollment letter, transcript.', contact: 'HEC: 051-90409100, Email: scholarship@hec.gov.pk', source: 'Higher Education Commission (HEC)' },
};

async function main() {
  console.log('=== FILLING EMPTY FIELDS ===\n');

  // Fix CM Programs - add deadlines and official URLs
  const cmPrograms = await p.cMProgram.findMany();
  let cmFixed = 0;
  for (const prog of cmPrograms) {
    const data = CM_URLS[prog.name];
    if (data) {
      await p.cMProgram.update({
        where: { id: prog.id },
        data: {
          officialUrl: data.url,
          deadline: new Date(data.deadline),
          isVerified: true,
        },
      });
      cmFixed++;
      console.log(`  ✓ CM: ${prog.name} — URL + deadline added`);
    } else {
      console.log(`  ⚠ CM: "${prog.name}" — no data found`);
    }
  }
  console.log(`\nCM Programs fixed: ${cmFixed}/${cmPrograms.length}\n`);

  // Fix Scholarships - add empty fields
  const scholarships = await p.scholarship.findMany();
  let schFixed = 0;
  for (const sch of scholarships) {
    const data = SCH_DATA[sch.name];
    if (data) {
      await p.scholarship.update({
        where: { id: sch.id },
        data: {
          eligibilityCriteria: data.eligibility,
          applicationProcess: data.process,
          documentsRequired: data.documents,
          contactInfo: data.contact,
          sourceName: data.source,
          verificationStatus: 'verified',
        },
      });
      schFixed++;
      console.log(`  ✓ SCH: ${sch.name} — 5 fields filled`);
    } else {
      console.log(`  ⚠ SCH: "${sch.name}" — no data found`);
    }
  }
  console.log(`\nScholarships fixed: ${schFixed}/${scholarships.length}`);
}

main().finally(() => p.$disconnect());
